//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anolis.Resourcer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Anolis.Resourcer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap ARF_SortByLCID {
            get {
                object obj = ResourceManager.GetObject("ARF_SortByLCID", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ARF_SortByName {
            get {
                object obj = ResourceManager.GetObject("ARF_SortByName", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Details {
            get {
                object obj = ResourceManager.GetObject("Details", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Dialogs_Run {
            get {
                object obj = ResourceManager.GetObject("Dialogs_Run", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Dir_Zoomable {
            get {
                object obj = ResourceManager.GetObject("Dir_Zoomable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon16 {
            get {
                object obj = ResourceManager.GetObject("Icon16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon32 {
            get {
                object obj = ResourceManager.GetObject("Icon32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon96 {
            get {
                object obj = ResourceManager.GetObject("Icon96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageViewer_Center {
            get {
                object obj = ResourceManager.GetObject("ImageViewer_Center", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageViewer_Information {
            get {
                object obj = ResourceManager.GetObject("ImageViewer_Information", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageViewer_Interpolation {
            get {
                object obj = ResourceManager.GetObject("ImageViewer_Interpolation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageViewer_TransparentBg {
            get {
                object obj = ResourceManager.GetObject("ImageViewer_TransparentBg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageViewer_Zoom100 {
            get {
                object obj = ResourceManager.GetObject("ImageViewer_Zoom100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageViewer_ZoomIn {
            get {
                object obj = ResourceManager.GetObject("ImageViewer_ZoomIn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageViewer_ZoomOut {
            get {
                object obj = ResourceManager.GetObject("ImageViewer_ZoomOut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NavBackOver {
            get {
                object obj = ResourceManager.GetObject("NavBackOver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NavBackUp {
            get {
                object obj = ResourceManager.GetObject("NavBackUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NavUpOver {
            get {
                object obj = ResourceManager.GetObject("NavUpOver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NavUpUp {
            get {
                object obj = ResourceManager.GetObject("NavUpUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TextViewer_Bom {
            get {
                object obj = ResourceManager.GetObject("TextViewer_Bom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TextViewer_Endian {
            get {
                object obj = ResourceManager.GetObject("TextViewer_Endian", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TextViewer_Font {
            get {
                object obj = ResourceManager.GetObject("TextViewer_Font", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TextViewer_WordWrap {
            get {
                object obj = ResourceManager.GetObject("TextViewer_WordWrap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Toolbar_GenOpt {
            get {
                object obj = ResourceManager.GetObject("Toolbar_GenOpt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Toolbar_GenOpt24 {
            get {
                object obj = ResourceManager.GetObject("Toolbar_GenOpt24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Toolbar_ResAdd {
            get {
                object obj = ResourceManager.GetObject("Toolbar_ResAdd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Toolbar_ResAdd24 {
            get {
                object obj = ResourceManager.GetObject("Toolbar_ResAdd24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Toolbar_ResCan {
            get {
                object obj = ResourceManager.GetObject("Toolbar_ResCan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Toolbar_ResCan24 {
            get {
                object obj = ResourceManager.GetObject("Toolbar_ResCan24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Toolbar_ResDel {
            get {
                object obj = ResourceManager.GetObject("Toolbar_ResDel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Toolbar_ResDel24 {
            get {
                object obj = ResourceManager.GetObject("Toolbar_ResDel24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Toolbar_ResExt {
            get {
                object obj = ResourceManager.GetObject("Toolbar_ResExt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Toolbar_ResExt24 {
            get {
                object obj = ResourceManager.GetObject("Toolbar_ResExt24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Toolbar_ResRep {
            get {
                object obj = ResourceManager.GetObject("Toolbar_ResRep", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Toolbar_ResRep24 {
            get {
                object obj = ResourceManager.GetObject("Toolbar_ResRep24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Toolbar_SrcOpen {
            get {
                object obj = ResourceManager.GetObject("Toolbar_SrcOpen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Toolbar_SrcOpen24 {
            get {
                object obj = ResourceManager.GetObject("Toolbar_SrcOpen24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Toolbar_SrcRev {
            get {
                object obj = ResourceManager.GetObject("Toolbar_SrcRev", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Toolbar_SrcRev24 {
            get {
                object obj = ResourceManager.GetObject("Toolbar_SrcRev24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Toolbar_SrcSave {
            get {
                object obj = ResourceManager.GetObject("Toolbar_SrcSave", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Toolbar_SrcSave24 {
            get {
                object obj = ResourceManager.GetObject("Toolbar_SrcSave24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Tree_Add {
            get {
                object obj = ResourceManager.GetObject("Tree_Add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Tree_Delete {
            get {
                object obj = ResourceManager.GetObject("Tree_Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Tree_Edit {
            get {
                object obj = ResourceManager.GetObject("Tree_Edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Type_Accelerator16 {
            get {
                object obj = ResourceManager.GetObject("Type_Accelerator16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Type_Accelerator32 {
            get {
                object obj = ResourceManager.GetObject("Type_Accelerator32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Type_Binary16 {
            get {
                object obj = ResourceManager.GetObject("Type_Binary16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Type_Binary32 {
            get {
                object obj = ResourceManager.GetObject("Type_Binary32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Type_Bitmap16 {
            get {
                object obj = ResourceManager.GetObject("Type_Bitmap16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Type_Bitmap32 {
            get {
                object obj = ResourceManager.GetObject("Type_Bitmap32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Type_ColorTable16 {
            get {
                object obj = ResourceManager.GetObject("Type_ColorTable16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Type_ColorTable32 {
            get {
                object obj = ResourceManager.GetObject("Type_ColorTable32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Type_Cursor16 {
            get {
                object obj = ResourceManager.GetObject("Type_Cursor16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Type_Cursor32 {
            get {
                object obj = ResourceManager.GetObject("Type_Cursor32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Type_Dialog16 {
            get {
                object obj = ResourceManager.GetObject("Type_Dialog16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Type_Dialog32 {
            get {
                object obj = ResourceManager.GetObject("Type_Dialog32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Type_File16 {
            get {
                object obj = ResourceManager.GetObject("Type_File16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Type_File32 {
            get {
                object obj = ResourceManager.GetObject("Type_File32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Type_Html16 {
            get {
                object obj = ResourceManager.GetObject("Type_Html16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Type_Html32 {
            get {
                object obj = ResourceManager.GetObject("Type_Html32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Type_Icon16 {
            get {
                object obj = ResourceManager.GetObject("Type_Icon16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Type_Icon32 {
            get {
                object obj = ResourceManager.GetObject("Type_Icon32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Type_Menu16 {
            get {
                object obj = ResourceManager.GetObject("Type_Menu16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Type_Menu32 {
            get {
                object obj = ResourceManager.GetObject("Type_Menu32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Type_StringTable16 {
            get {
                object obj = ResourceManager.GetObject("Type_StringTable16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Type_StringTable32 {
            get {
                object obj = ResourceManager.GetObject("Type_StringTable32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Type_Toolbar16 {
            get {
                object obj = ResourceManager.GetObject("Type_Toolbar16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Type_Toolbar32 {
            get {
                object obj = ResourceManager.GetObject("Type_Toolbar32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Type_Version16 {
            get {
                object obj = ResourceManager.GetObject("Type_Version16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Type_Version32 {
            get {
                object obj = ResourceManager.GetObject("Type_Version32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Type_Xml16 {
            get {
                object obj = ResourceManager.GetObject("Type_Xml16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Type_Xml32 {
            get {
                object obj = ResourceManager.GetObject("Type_Xml32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ZPB_Empty {
            get {
                object obj = ResourceManager.GetObject("ZPB_Empty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
