//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anolis.Resourcer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Anolis.Resourcer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (C) 1989, 1991 Free Software Foundation, Inc.
        ///59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
        ///
        ///Everyone is permitted to copy and distribute verbatim copies
        ///of this license document, but changing it is not allowed.
        ///
        ///Preamble
        ///
        ///The licenses for most software are designed to take away your freedom to share and change it. By contrast, the GNU General Public License is intended to guarantee your freedom to share and change free software--to make sure the software is free for all its users. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AnolisGplLicense {
            get {
                return ResourceManager.GetString("AnolisGplLicense", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ARF_SortByLCID {
            get {
                object obj = ResourceManager.GetObject("ARF_SortByLCID", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ARF_SortByName {
            get {
                object obj = ResourceManager.GetObject("ARF_SortByName", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Dir_Zoomable {
            get {
                object obj = ResourceManager.GetObject("Dir_Zoomable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageViewer_Center {
            get {
                object obj = ResourceManager.GetObject("ImageViewer_Center", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageViewer_Interpolation {
            get {
                object obj = ResourceManager.GetObject("ImageViewer_Interpolation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageViewer_TransparentBg {
            get {
                object obj = ResourceManager.GetObject("ImageViewer_TransparentBg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageViewer_Zoom100 {
            get {
                object obj = ResourceManager.GetObject("ImageViewer_Zoom100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageViewer_ZoomIn {
            get {
                object obj = ResourceManager.GetObject("ImageViewer_ZoomIn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageViewer_ZoomOut {
            get {
                object obj = ResourceManager.GetObject("ImageViewer_ZoomOut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TextViewer_Bom {
            get {
                object obj = ResourceManager.GetObject("TextViewer_Bom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TextViewer_Endian {
            get {
                object obj = ResourceManager.GetObject("TextViewer_Endian", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TextViewer_Font {
            get {
                object obj = ResourceManager.GetObject("TextViewer_Font", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TextViewer_WordWrap {
            get {
                object obj = ResourceManager.GetObject("TextViewer_WordWrap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Toolbar_Options {
            get {
                object obj = ResourceManager.GetObject("Toolbar_Options", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Toolbar_ResAdd {
            get {
                object obj = ResourceManager.GetObject("Toolbar_ResAdd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Toolbar_ResDel {
            get {
                object obj = ResourceManager.GetObject("Toolbar_ResDel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Toolbar_ResExt {
            get {
                object obj = ResourceManager.GetObject("Toolbar_ResExt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Toolbar_ResRep {
            get {
                object obj = ResourceManager.GetObject("Toolbar_ResRep", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Toolbar_ResRev {
            get {
                object obj = ResourceManager.GetObject("Toolbar_ResRev", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Toolbar_SrcOpen {
            get {
                object obj = ResourceManager.GetObject("Toolbar_SrcOpen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Toolbar_SrcRev {
            get {
                object obj = ResourceManager.GetObject("Toolbar_SrcRev", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Toolbar_SrcSave {
            get {
                object obj = ResourceManager.GetObject("Toolbar_SrcSave", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ZPB_Empty {
            get {
                object obj = ResourceManager.GetObject("ZPB_Empty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
